import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GalleryHorizontal, Home } from "lucide-react";
import { FloatingNav } from "@/components/ui/FloatingNavbar";
import Footer from "@/components/ui/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

  const navItems = [
    {
      name: "Home",
      link: "/",
      icon: <Home className="h-4 w-4 text-neutral-500 dark:text-white" />,
    },   
     {
      name: "Projects",
      link: "#projects",
      icon: <GalleryHorizontal className="h-4 w-4 text-neutral-500 dark:text-white" />,
    },
  ]

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FloatingNav
          navItems={navItems}
          className=""
        />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
